-- Nudge Chapters — personal command centre (finance module)
-- Initial schema for Supabase (PostgreSQL).
--
-- Design notes
--  * Every user-owned row carries user_id (defaults to auth.uid()) and is protected
--    by row-level security, so a signed-in user can only ever see their own data.
--  * Money is numeric(16,2). Dates that represent financial events are plain `date`
--    (no time zone) so recurring schedules never drift across time zones.
--  * Actual transactions live in `transactions`. Planned/expected events are
--    generated by the app's projection engine from rules, cards, loans, chits,
--    SIPs and lendings; `event_overrides` records skips/reschedules of planned
--    events, and a transaction that settles a planned event stores
--    (rule_id, occurrence_date) so plans and actuals are never double-counted.
--  * Every change to a financial table is written to `audit_events` by trigger.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Identity
-- ---------------------------------------------------------------------------

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  name text,
  country text not null default 'IN',
  currency text not null default 'INR',
  locale text not null default 'en-IN',
  timezone text not null default 'Asia/Kolkata',
  birth_year int check (birth_year between 1900 and 2100),
  retirement_age int not null default 60 check (retirement_age between 30 and 100),
  life_expectancy int not null default 85 check (life_expectancy between 40 and 120),
  mode text not null default 'simple' check (mode in ('simple', 'advanced')),
  onboarding_done boolean not null default false,
  assumptions jsonb not null default '{}'::jsonb,
  preferences jsonb not null default '{}'::jsonb,
  fx_rates jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Create a profile row automatically when someone signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Ledger: accounts, categories, transactions
-- ---------------------------------------------------------------------------

create table public.accounts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name text not null check (length(name) between 1 and 120),
  type text not null default 'savings'
    check (type in ('savings', 'current', 'cash', 'wallet', 'other')),
  institution text,
  currency text not null default 'INR',
  opening_balance numeric(16,2) not null default 0,
  opening_date date not null default current_date,
  min_balance numeric(16,2) not null default 0 check (min_balance >= 0),
  include_in_cash boolean not null default true,
  is_emergency_fund boolean not null default false,
  last_verified_at date,
  archived boolean not null default false,
  color text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.categories (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name text not null check (length(name) between 1 and 60),
  kind text not null check (kind in ('income', 'expense')),
  is_fixed boolean not null default false,
  is_essential boolean not null default false,
  color text,
  archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, kind, name)
);

create table public.credit_cards (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name text not null check (length(name) between 1 and 120),
  issuer text,
  last4 text check (last4 is null or last4 ~ '^[0-9]{4}$'),
  network text,
  credit_limit numeric(16,2) not null default 0 check (credit_limit >= 0),
  statement_day int not null check (statement_day between 1 and 31),
  due_day int not null check (due_day between 1 and 31),
  payment_account_id uuid references public.accounts (id) on delete set null,
  opening_outstanding numeric(16,2) not null default 0,
  opening_date date not null default current_date,
  expected_monthly_spend numeric(16,2) not null default 0 check (expected_monthly_spend >= 0),
  annual_fee numeric(16,2) not null default 0 check (annual_fee >= 0),
  interest_rate_apr numeric(6,2) not null default 42 check (interest_rate_apr >= 0),
  reward_points numeric(16,2) not null default 0,
  color text,
  archived boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.card_statements (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  card_id uuid not null references public.credit_cards (id) on delete cascade,
  statement_date date not null,
  due_date date not null,
  total_due numeric(16,2) not null check (total_due >= 0),
  min_due numeric(16,2) not null default 0 check (min_due >= 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (due_date >= statement_date),
  unique (card_id, statement_date)
);

create table public.loans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name text not null check (length(name) between 1 and 120),
  lender text,
  type text not null default 'personal'
    check (type in ('home', 'personal', 'vehicle', 'education', 'gold', 'card_emi', 'consumer', 'other')),
  principal numeric(16,2) not null check (principal > 0),
  interest_rate numeric(6,3) not null default 0 check (interest_rate >= 0),
  interest_type text not null default 'reducing' check (interest_type in ('reducing', 'flat')),
  tenure_months int not null check (tenure_months between 1 and 600),
  emi_amount numeric(16,2) check (emi_amount is null or emi_amount > 0),
  first_emi_date date not null,
  emis_paid_offset int not null default 0 check (emis_paid_offset >= 0),
  payment_account_id uuid references public.accounts (id) on delete set null,
  card_id uuid references public.credit_cards (id) on delete set null,
  processing_fee numeric(16,2) not null default 0,
  status text not null default 'active' check (status in ('active', 'closed')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.chits (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name text not null check (length(name) between 1 and 120),
  provider text,
  chit_value numeric(16,2) not null check (chit_value > 0),
  monthly_contribution numeric(16,2) not null check (monthly_contribution > 0),
  installments int not null check (installments between 1 and 240),
  start_date date not null,
  installments_paid_offset int not null default 0 check (installments_paid_offset >= 0),
  payout_status text not null default 'pending' check (payout_status in ('pending', 'received')),
  payout_amount numeric(16,2),
  payout_date date,
  commission_pct numeric(5,2) not null default 5 check (commission_pct between 0 and 100),
  auction_notes text,
  account_id uuid references public.accounts (id) on delete set null,
  status text not null default 'active' check (status in ('active', 'completed', 'closed')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.goals (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name text not null check (length(name) between 1 and 120),
  kind text not null default 'other'
    check (kind in ('emergency', 'house', 'vehicle', 'travel', 'education', 'retirement', 'wedding', 'gadget', 'other')),
  target_amount numeric(16,2) not null check (target_amount > 0),
  target_date date,
  current_amount numeric(16,2) not null default 0 check (current_amount >= 0),
  monthly_contribution numeric(16,2) not null default 0 check (monthly_contribution >= 0),
  linked_account_ids uuid[] not null default '{}',
  linked_investment_ids uuid[] not null default '{}',
  priority int not null default 2 check (priority between 1 and 3),
  expected_return numeric(6,2),
  color text,
  archived boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.investments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  type text not null check (type in (
    'mutual_fund', 'stock', 'etf', 'epf', 'ppf', 'nps', 'fd', 'rd', 'gold',
    'bond', 'real_estate', 'vehicle', 'crypto', 'other')),
  name text not null check (length(name) between 1 and 160),
  institution text,
  identifier text,
  asset_class text not null default 'equity'
    check (asset_class in ('equity', 'debt', 'hybrid', 'gold', 'real_estate', 'cash', 'other')),
  units numeric(20,6),
  avg_cost numeric(16,4),
  current_price numeric(16,4),
  invested_amount numeric(16,2) not null default 0,
  current_value numeric(16,2),
  value_as_of date,
  expected_return numeric(6,2),
  interest_rate numeric(6,3),
  start_date date,
  maturity_date date,
  sip_amount numeric(16,2) not null default 0 check (sip_amount >= 0),
  sip_day int check (sip_day is null or sip_day between 1 and 31),
  sip_account_id uuid references public.accounts (id) on delete set null,
  sip_active boolean not null default false,
  track_from date not null default current_date,
  employee_contribution numeric(16,2) not null default 0,
  employer_contribution numeric(16,2) not null default 0,
  pension_contribution numeric(16,2) not null default 0,
  is_international boolean not null default false,
  currency text not null default 'INR',
  goal_id uuid references public.goals (id) on delete set null,
  archived boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Historical valuation points (EPFO passbook updates, NAV/price updates, property revaluations).
create table public.investment_valuations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  investment_id uuid not null references public.investments (id) on delete cascade,
  date date not null,
  value numeric(16,2) not null,
  price numeric(16,4),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.lendings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  direction text not null default 'lent' check (direction in ('lent', 'borrowed')),
  person text not null check (length(person) between 1 and 120),
  amount numeric(16,2) not null check (amount > 0),
  date date not null,
  expected_date date,
  interest_rate numeric(6,3) not null default 0 check (interest_rate >= 0),
  account_id uuid references public.accounts (id) on delete set null,
  include_in_projection boolean not null default true,
  written_off boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.reserves (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name text not null check (length(name) between 1 and 120),
  target_amount numeric(16,2) not null default 0 check (target_amount >= 0),
  current_amount numeric(16,2) not null default 0 check (current_amount >= 0),
  monthly_funding numeric(16,2) not null default 0 check (monthly_funding >= 0),
  due_date date,
  color text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Planning: recurring rules and overrides of generated events
-- ---------------------------------------------------------------------------

create table public.recurring_rules (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name text not null check (length(name) between 1 and 120),
  kind text not null check (kind in ('income', 'expense', 'transfer')),
  amount numeric(16,2) not null check (amount > 0),
  frequency text not null default 'monthly'
    check (frequency in ('once', 'weekly', 'biweekly', 'monthly', 'quarterly', 'half_yearly', 'yearly', 'custom')),
  interval_days int check (interval_days is null or interval_days between 1 and 3650),
  day_of_month int check (day_of_month is null or day_of_month between 1 and 31),
  start_date date not null,
  end_date date,
  track_from date not null default current_date,
  account_id uuid references public.accounts (id) on delete set null,
  to_account_id uuid references public.accounts (id) on delete set null,
  card_id uuid references public.credit_cards (id) on delete set null,
  category text,
  is_fixed boolean not null default true,
  is_essential boolean not null default false,
  is_subscription boolean not null default false,
  certainty text not null default 'known' check (certainty in ('known', 'expected', 'uncertain')),
  growth_pct numeric(6,2),
  tax_deducted numeric(16,2) not null default 0,
  active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date is null or end_date >= start_date),
  check (kind <> 'transfer' or to_account_id is not null)
);

create table public.event_overrides (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  source_type text not null check (source_type in ('rule', 'sip', 'loan', 'chit', 'card', 'lending')),
  source_id uuid not null,
  occurrence_date date not null,
  action text not null check (action in ('skip', 'cancel', 'reschedule', 'adjust')),
  new_date date,
  new_amount numeric(16,2),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, source_type, source_id, occurrence_date)
);

create table public.transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  date date not null,
  type text not null check (type in (
    'income', 'expense', 'transfer', 'card_spend', 'card_payment',
    'lend', 'lend_repayment', 'borrow', 'borrow_repayment',
    'invest_buy', 'invest_sell', 'loan_emi', 'loan_prepayment',
    'chit_installment', 'chit_payout', 'adjustment')),
  amount numeric(16,2) not null,
  account_id uuid references public.accounts (id) on delete set null,
  to_account_id uuid references public.accounts (id) on delete set null,
  card_id uuid references public.credit_cards (id) on delete set null,
  statement_id uuid references public.card_statements (id) on delete set null,
  loan_id uuid references public.loans (id) on delete set null,
  chit_id uuid references public.chits (id) on delete set null,
  investment_id uuid references public.investments (id) on delete set null,
  lending_id uuid references public.lendings (id) on delete set null,
  rule_id uuid references public.recurring_rules (id) on delete set null,
  occurrence_date date,
  is_partial boolean not null default false,
  category text,
  description text,
  notes text,
  units numeric(20,6),
  price numeric(16,4),
  principal_part numeric(16,2),
  interest_part numeric(16,2),
  reconciled boolean not null default false,
  import_hash text,
  tags text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- Only balance adjustments may be negative; every other amount is a positive magnitude
  -- whose direction comes from the transaction type.
  check (amount >= 0 or type = 'adjustment'),
  check (type <> 'transfer' or (account_id is not null and to_account_id is not null and account_id <> to_account_id)),
  unique (user_id, import_hash)
);

-- ---------------------------------------------------------------------------
-- History & audit
-- ---------------------------------------------------------------------------

create table public.net_worth_snapshots (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  date date not null,
  cash numeric(16,2) not null default 0,
  investments numeric(16,2) not null default 0,
  other_assets numeric(16,2) not null default 0,
  liabilities numeric(16,2) not null default 0,
  net_worth numeric(16,2) not null default 0,
  breakdown jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, date)
);

create table public.audit_events (
  id bigint generated always as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  table_name text not null,
  record_id uuid,
  action text not null check (action in ('insert', 'update', 'delete')),
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.audit_row()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid;
  v_id uuid;
begin
  if tg_op = 'DELETE' then
    v_user := old.user_id;
    v_id := old.id;
  else
    v_user := new.user_id;
    v_id := new.id;
  end if;

  -- Skip when the owning user is being deleted (cascade) — nothing left to audit.
  if not exists (select 1 from auth.users u where u.id = v_user) then
    return null;
  end if;

  insert into public.audit_events (user_id, table_name, record_id, action, old_data, new_data)
  values (
    v_user,
    tg_table_name,
    v_id,
    lower(tg_op),
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) end
  );
  return null;
end;
$$;

-- ---------------------------------------------------------------------------
-- Triggers, indexes and row-level security for every user-owned table
-- ---------------------------------------------------------------------------

do $$
declare
  t text;
  audited text[] := array[
    'accounts', 'categories', 'credit_cards', 'card_statements', 'loans', 'chits',
    'goals', 'investments', 'investment_valuations', 'lendings', 'reserves',
    'recurring_rules', 'event_overrides', 'transactions'];
  owned text[] := audited || array['net_worth_snapshots'];
begin
  foreach t in array owned loop
    execute format('alter table public.%I enable row level security', t);
    execute format('create index %I on public.%I (user_id)', t || '_user_idx', t);
    execute format(
      'create trigger %I before update on public.%I for each row execute function public.set_updated_at()',
      t || '_updated_at', t);
    execute format(
      'create policy %I on public.%I for select to authenticated using ((select auth.uid()) = user_id)',
      t || '_select_own', t);
    execute format(
      'create policy %I on public.%I for insert to authenticated with check ((select auth.uid()) = user_id)',
      t || '_insert_own', t);
    execute format(
      'create policy %I on public.%I for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)',
      t || '_update_own', t);
    execute format(
      'create policy %I on public.%I for delete to authenticated using ((select auth.uid()) = user_id)',
      t || '_delete_own', t);
  end loop;

  foreach t in array audited loop
    execute format(
      'create trigger %I after insert or update or delete on public.%I for each row execute function public.audit_row()',
      t || '_audit', t);
  end loop;
end;
$$;

-- Profiles: keyed by the auth user id.
alter table public.profiles enable row level security;
create trigger profiles_updated_at before update on public.profiles
  for each row execute function public.set_updated_at();
create policy profiles_select_own on public.profiles for select to authenticated
  using ((select auth.uid()) = id);
create policy profiles_insert_own on public.profiles for insert to authenticated
  with check ((select auth.uid()) = id);
create policy profiles_update_own on public.profiles for update to authenticated
  using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

-- Audit log: readable by its owner, written only by the trigger.
alter table public.audit_events enable row level security;
create index audit_events_user_created_idx on public.audit_events (user_id, created_at desc);
create policy audit_events_select_own on public.audit_events for select to authenticated
  using ((select auth.uid()) = user_id);

-- Foreign-key and query indexes
create index transactions_user_date_idx on public.transactions (user_id, date desc);
create index transactions_account_idx on public.transactions (account_id);
create index transactions_to_account_idx on public.transactions (to_account_id);
create index transactions_card_idx on public.transactions (card_id);
create index transactions_statement_idx on public.transactions (statement_id);
create index transactions_loan_idx on public.transactions (loan_id);
create index transactions_chit_idx on public.transactions (chit_id);
create index transactions_investment_idx on public.transactions (investment_id);
create index transactions_lending_idx on public.transactions (lending_id);
create index transactions_rule_occurrence_idx on public.transactions (rule_id, occurrence_date);
create index card_statements_card_idx on public.card_statements (card_id, statement_date desc);
create index credit_cards_payment_account_idx on public.credit_cards (payment_account_id);
create index loans_payment_account_idx on public.loans (payment_account_id);
create index loans_card_idx on public.loans (card_id);
create index chits_account_idx on public.chits (account_id);
create index investments_sip_account_idx on public.investments (sip_account_id);
create index investments_goal_idx on public.investments (goal_id);
create index investment_valuations_investment_idx on public.investment_valuations (investment_id, date desc);
create index lendings_account_idx on public.lendings (account_id);
create index recurring_rules_account_idx on public.recurring_rules (account_id);
create index recurring_rules_to_account_idx on public.recurring_rules (to_account_id);
create index recurring_rules_card_idx on public.recurring_rules (card_id);
create index event_overrides_source_idx on public.event_overrides (source_type, source_id);

-- ---------------------------------------------------------------------------
-- Account deletion ("delete my data")
-- ---------------------------------------------------------------------------

-- Deletes the signed-in user. Every table cascades from auth.users, so this
-- permanently removes all of the user's financial data as well.
create or replace function public.delete_my_account()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
begin
  if v_user is null then
    raise exception 'Not signed in';
  end if;
  delete from auth.users where id = v_user;
end;
$$;

revoke all on function public.delete_my_account() from public, anon;
grant execute on function public.delete_my_account() to authenticated;

-- Internal trigger functions must not be callable through the API.
revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.audit_row() from public, anon, authenticated;
